language: node_js
node_js:
- '0.10'
- '0.12'
- '4.1.0'
before_script:
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt-get update -qq
- sudo apt-get install -qq bats
- npm install -g https://github.com/uditalias/swamp/tarball/master
script:
- cd test && bats bats 

after_success:
notifications:
  email:
  - udi.talias@gmail.com
